update the installer

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,6 +1,65 @@
-#! /bin/sh
+#!/bin/bash
 
-gem install kramdown
-brew install jq # https://robots.thoughtbot.com/jq-is-sed-for-json
+# Resolve all dependencies that the application requires to run.
+# From https://github.com/github/scripts-to-rule-them-all/blob/master/script/bootstrap
+
+# This will install jq ( https://robots.thoughtbot.com/jq-is-sed-for-json )
 git clone https://github.com/Connexions/rhaptos.cnxmlutils
-npm install
+
+cd "$(dirname "$0")/.."
+
+if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
+  >&2 echo "==> Updating Homebrew…"
+  brew update || exit 1
+
+  brew bundle check >/dev/null 2>&1  || {
+    >&2 echo "==> Installing Homebrew dependencies…"
+    brew bundle || exit 1
+  }
+fi
+
+# Note: Skip rbenv for Travis because it already has ruby
+if [[ ! "${CI}" = "true" ]] && [[ -f ".ruby-version" ]]; then
+  if [[ -n $(which rbenv) ]]; then
+
+    if [[ -z "$(rbenv version-name 2>/dev/null)" ]]; then
+      >&2 echo "==> Installing Ruby…"
+      rbenv install --skip-existing || exit 1
+    fi
+  else
+    >&2 echo "WARNING: Skipping rbenv. Using local ruby"
+  fi
+
+  # Initialize rbenv (if installed)
+  [[ -n $(which rbenv) ]] && eval "$(rbenv init -)"
+
+  which bundle >/dev/null 2>&1  || {
+    >&2 echo "==> Installing Ruby Bundler gem…"
+    gem install bundler || {
+      >&2 echo ''
+      >&2 echo ''
+      >&2 echo '--------------- Error -------------'
+      >&2 echo 'Problem installing ruby bundler.'
+      exit 1
+    }
+
+    [[ -n $(which rbenv) ]] && rbenv rehash || ( echo "Problem running rbenv rehash" && exit 1)
+
+  }
+fi
+
+if [[ -f "Gemfile" ]]; then
+  >&2 echo "==> Installing gem dependencies…"
+  which bundle
+  bundle check --path vendor/gems >/dev/null 2>&1  || {
+    bundle install --path vendor/gems --quiet --without production || exit 1
+  }
+fi
+
+
+>&2 echo "==> Installing Node package dependencies"
+>&2 echo "Using node: $(node --version)"
+>&2 echo "Using npm: $(npm --version)"
+npm install || exit 1
+
+>&2 echo "==> Bootstrap succeeded"
diff --git a/script/start b/script/start
--- a/script/start
+++ b/script/start
@@ -5,7 +5,7 @@ SINGLE_BOOK_REPO_NAME=${1}
 # Check if dependencies are installed
 test -z "$(curl --version)" && (echo "curl was not found"; exit 1)
 test -z "$(xsltproc --version)" && (echo "xsltproc was not found"; exit 1)
-test -z "$(kramdown --version)" && (echo "kramdown was not found. try running script/bootstrap first"; exit 1)
+test -z "$(rbenv exec bundle exec kramdown --version)" && (echo "kramdown was not found. try running script/bootstrap first"; exit 1)
 test -z "$(jq --version)" && (echo "jq was not found. try running script/bootstrap first"; exit 1)
 if [ ! -d "./rhaptos.cnxmlutils" ]
 then
@@ -23,6 +23,7 @@ eval $(parse_yaml _config.yml "config_")
 # access yaml content
 # BOOK_COUNT=${#config_books__title[@]}
 
+BOOKS_WITH_ERRORS=()
 INDEX=0
 for BOOK_TITLE in "${config_books__title[@]}"
 do
@@ -39,7 +40,7 @@ do
     then
       echo "Generating" ${INDEX} ${UUID} ${LICENSE} ${REPO_NAME} ${BOOK_TITLE}
       ./script/do.sh "${REPO_NAME}" "${UUID}" "${BOOK_TITLE}" "${LICENSE}"
-      test $? != 0 && exit 1
+      test $? != 0 && BOOKS_WITH_ERRORS+="${REPO_NAME}"
     fi
   else
     echo "Error in _config.yml for book" ${INDEX} ${BOOK_TITLE} ${UUID}
@@ -47,3 +48,5 @@ do
   fi
   INDEX=$[INDEX + 1]
 done
+
+echo "Books with errors: ${BOOKS_WITH_ERRORS[@]}"
